### ISSUE TITLE
Too many files needs editing when copied from reference plugin

### ISSUE THREAD

**Issue by leamas** [Rasbats/UKTides_pi#6]
The idea is that the number of files which should need editing when copied from the shipdriver reference plugin should be limited. In particular, there should be no need to edit the files under cmake/. 

However: https://github.com/Rasbats/UKTides_pi/pull/4#issuecomment-744032251 Following up on this: which files under cmake needs editing?

The list of files currently known to need editing:

  -  CMakeLists.txt
  -  UKTides-plugin.xml.in
  -  org.opencpn.OpenCPN.Plugin.UKTides.yaml
  -  appveyor.yml
  -  ci/circleci-build-flatpak.sh
  - README.md

This list now looks sound to me. The bulk of the setup is in CMakelists.txt and, to a minor extent, the flatpak .yaml manifest. This is just work that has to be done for each plugin. 

The t rest is basically applying the name, git repo etc. It shouldn't be a problem with some docs describing what to do.

EDIT: Fix after applying #9.
EDIT2: Adding README.md

**Comment by Rasbats** [comment]
Please add this one to the list:

- ci/circleci-build-flatpak.sh
Edit: I have aligned all the files with ShipDriver, including the chmod for scripts. Builds are fine on Appveyor, Travis and CircleCI.

**Comment by leamas** [comment]
Done. 

Which file(s) under cmake/ needs editing?

**Comment by Rasbats** [comment]
[https://github.com/Rasbats/shipdriver_pi/issues/92](url)

>No, all the cmake/ files from ShipDriver have been used as is for UKTides. Intend documenting the ones in other folders that need editing idc.

**Comment by leamas** [comment]
So, dropping two of the files in that list, and cleaning up circle-build-flatpak so the code is sound and simple to edit.

Great that cmake/ seem to survive...

**Comment by leamas** [comment]
You are fast, indeed ;) Editing list on top of this issue. I'm basically happy. Are you?

**Comment by Rasbats** [comment]
Always! (Well nearly). 
Just tested again with both ShipDriver and UKTides using the batch file. Still not able to find wxWidgets. 
There was a bug in CMake - FindwxWidgets.cmake. Referenced by this:
```
if(MSYS)
            # this is to convert msys to windows paths, and handle the missing /usr
            string(REGEX REPLACE "/usr/local" ";C:/MinGW/msys/1.0/local" wxWidgets_INCLUDE_DIRS ${wxWidgets_INCLUDE_DIRS})
        endif(MSYS)
```
Is FindwxWidgets.cmake invoked anywhere?

**Comment by leamas** [comment]
Adding README.md to the list of files requiring editing. This needs to be that way.

**Comment by leamas** [comment]
> Is FindwxWidgets.cmake invoked anywhere?

Still stuck? Yes, it's invoked in PluginLibs.cmake by  `find_package(wxWidgets COMPONENTS ${_LIBS} REQUIRED)` which eventually maps to a FindwxWidgets.cmake invocation. 

Don't blame me for the cmake syntax...

The core issue: is it missing  despite it's installed? Or is it just not installed according to DEPENDENCIES.md?

**Comment by leamas** [comment]
Can we close this issue, feeling happy with the kind of edits being required when applying the "framework" to  another plugin?

**Comment by Rasbats** [comment]
Yes please. I am working on using the framework from ShipDriver for another plugin that has not been 'touched'. This as part of the document I am working on.

**Comment by leamas** [comment]
OK. closing Thanks for all your work!

And sorry for being "hard task master", cannot forget that one ;)
